### PR TITLE
Add servantSpec functions that allow passing a context

### LINKED ISSUE #42: servant-based test for APIs that need a context
I'd like to write tests for a servant-backed webservice where the API requires a context. A simple example is an API with basic auth, like described in the cookbook: https://docs.servant.dev/en/stable/cookbook/basic-auth/BasicAuth.html

I think that could be solved by adding `servantSpec` and `servantSpecWithSetupFunc` variants for APIs that take a context and under the hood use `serveWithContext`. What do you think? I'm happy to give it a try in a PR if that's something you'd like to have in the library.

### PR DESCRIPTION
**Pull request by L7R7**
This addresses #42. I tried to be as minimal as possible in the test (maybe it's even a bit too simplistic, but it's enough to show that it works) 

Closes #42

### CODE REVIEW

**Comment by L7R7** [comment]
It's a draft for now because I'm sure I'm not done yet. I'm struggling with the nix setup on my machine so I can't get proper feedback locallly yet

**Comment by L7R7** [comment]
It's a draft for now because I'm sure I'm not done yet. I'm struggling with the nix setup on my machine so I can't get proper feedback locallly yet

**Comment by NorfairKing** [comment]
Looks pretty good!

**Comment by L7R7** [comment]
Ok, so I am actually quite happy with what is there. I'd like to add a test that makes sure that access is forbidden when using wrong credentials but I'm stuck because I can't figure out how to properly catch the error servant-client will throw in this case.

I also thought about reducing code duplication a bit by delegatng `clientEnvSetupFunc` to `clientEnvSetupFuncWithContext` using `EmptyContext`, but I think it's good enough the way it is now. If you want that, I can add it.

**Comment by L7R7** [comment]
Oh, let me know if you think it's tested well enough already. I'd remove `clientGetWrongCredentials` then

**Comment by NorfairKing** [comment]
> I can't figure out how to properly catch the error servant-client will throw in this case.

You use `runClientM` manually:

```
it "foobar" $ \clientEnv -> do
  errOrResult <- runClientM functionHere clientEnv
```

**Comment by L7R7** [comment]
Thanks for the hint! I'll have to figure out how that works, but I can say it's nice to use :+1: 

I'm happy with the changes now. Let me know what you think

**Comment by NorfairKing** [comment]
@L7R7 Before we continue, just to be sure: are you aware of and in agreement with the license?

**Comment by L7R7** [comment]
Yes, I am and I'm fine with it

**Comment by NorfairKing** [comment]
Merged and released, Great thanks!

**Pull request merged**
