### PR TITLE
Do the -w -Wall trick for sydtest-discover

### PR DESCRIPTION
**Pull request by NorfairKing**
CC @murcake

### CODE REVIEW

**Comment by NorfairKing** [comment]
@murcake does this do what you want?

**Comment by murcake** [comment]
Hey, @NorfairKing, seems exactly right)

**Comment by murcake** [comment]
> Merged manually

What do you mean by manually?

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/sydtest/commit/ff224861ea409a9ee08576adb0438bbbb948917f It's released here.

**Comment by murcake** [comment]
Oh, okay, I see. Should #54 be mentioned in the commit to provide context for the change? That would also automatically close it, if in github-supported syntax. Anyway, closing the issue now. 

When will this be released oh hackage?

**Pull request closed without merging**
